name: publish container images
on:
  push:
    branches:
      - adding-k8s-overview-page
  workflow_dispatch:

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: lprabhu/pipelines-console-plugin
          tags: latest
          containerfiles: |
            ./Dockerfile

      # Podman Login action (https://github.com/redhat-actions/podman-login) also be used to log in,
      # in which case 'username' and 'password' can be omitted.
      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/lprabhu
          username: lprabhu
          password: U_pick_1t

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
